include:
  - project: reductech/templates/cicd/dotnet
    file: .gitlab-ci.linux.yml

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PACKAGE_NAME_NUGET: Reductech.Sequence.Connectors.Relativity
  PACKAGE_NAME_DLL: Reductech.Sequence.Connectors.Relativity
  PUBLISH_CONNECTOR: 1

build dev:
  needs:
    - project: reductech/sequence/connectors/entityimportclient
      job: package exe dev
      ref: main
      artifacts: true
  artifacts:
    paths:
      - Sequence.EntityImportClient/
      - '**/bin'
      - '**/obj'
    expire_in: 2 hours

build release:
  needs:
    - project: reductech/sequence/connectors/entityimportclient
      job: sign exe release
      ref: v0.1.1
      artifacts: true

test dev:
  script:
    - dotnet test --no-build --configuration $CONFIG --collect:"XPlat Code Coverage" --results-directory ./
      --filter "Category!=Integration&Category!=IntegrationShort"
      --settings coverlet.runsettings
    - >-
      pwsh -Command '$report = Get-Content -Path "*/coverage.cobertura.xml" -Raw ;
      $fixPaths = $report -replace "filename=`".+?${env:CI_PROJECT_NAME}(/|\\)", "filename=`"" ;
      [System.IO.File]::WriteAllText("./coverage.$($env:CI_JOB_NAME -replace "[^\w]+", "-").xml", $fixPaths)'

package connector dev:
  needs:
    - build dev
    - test dev
    - version check dev

package connector release:
  needs:
    - build release
    - test release
    - version check release
