include:
  - project: sequence/templates/cicd
    file: .gitlab-ci.linux.yml

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PACKAGE_NAME_NUGET: Sequence.Connectors.Relativity
  PACKAGE_NAME_DLL: Sequence.Connectors.Relativity
  PUBLISH_CONNECTOR: 1
  PUBLISH_NUGETORG: 1

build dev:
  needs:
    - project: sequence/connectors/entityimportclient
      job: package exe dev
      ref: main
      artifacts: true
  artifacts:
    paths:
      - Sequence.EntityImportClient/
      - '**/bin'
      - '**/obj'
    expire_in: 2 hours

build release:
  needs:
    - project: sequence/connectors/entityimportclient
      job: sign exe release
      ref: v0.5.0
      artifacts: true

test dev:
  script:
    - dotnet test --no-build --configuration $CONFIG --collect:"XPlat Code Coverage" --results-directory ./
      --filter "Category!=Integration&Category!=IntegrationShort"
      --settings coverlet.runsettings

package connector dev:
  needs:
    - build dev
    - test dev
    - version check dev

package connector release:
  needs:
    - build release
    - test release
    - version check release
