include:
  - project: reductech/templates/cicd/dotnet
    file: .gitlab-ci.linux.yml

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PACKAGE_NAME_NUGET: Reductech.EDR.Connectors.Relativity
  PACKAGE_NAME_DLL: Reductech.EDR.Connectors.Relativity
  PUBLISH_CONNECTOR: 1

build dev:
  artifacts:
    paths:
      - '**/bin'
      - '**/obj'
    expire_in: 2 hours

test dev:
  script:
    - dotnet test --no-build --configuration $CONFIG --collect:"XPlat Code Coverage" --results-directory ./
      --filter "Category!=Integration&Category!=IntegrationShort"
      --settings coverlet.runsettings
    - >-
      pwsh -Command '$report = Get-Content -Path "*/coverage.cobertura.xml" -Raw ;
      $fixPaths = $report -replace "filename=`".+?${env:CI_PROJECT_NAME}(/|\\)", "filename=`"" ;
      [System.IO.File]::WriteAllText("./coverage.$($env:CI_JOB_NAME -replace "[^\w]+", "-").xml", $fixPaths)'

